### ISSUE TITLE
py2neo.errors.ClientError: [Request.InvalidFormat] Could not parse the incoming JSON

### ISSUE THREAD

**Issue by hamzaziizzz** [arghyadeep99/Aarogya-Bot#21]
@arghyadeep99 @neelansh15 @nachiketbhuta 

After running `python3 build_medicalgraph.py`, it prints the values from 1 to 674, but for the second time the count stops to 304 and outputs the following error:
```
Traceback (most recent call last):
  File "/home/hamza/Aarogya-Bot/./api/build_medicalgraph.py", line 149, in <module>
    handler.create_graphnodes()
  File "/home/hamza/Aarogya-Bot/./api/build_medicalgraph.py", line 91, in create_graphnodes
    self.create_diseases_nodes(disease_infos)
  File "/home/hamza/Aarogya-Bot/./api/build_medicalgraph.py", line 84, in create_diseases_nodes
    self.g.create(node)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 591, in create
    self.update(lambda tx: tx.create(subgraph))
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 445, in update
    self._update(cypher, timeout=timeout)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 470, in _update
    value = f(tx)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 591, in <lambda>
    self.update(lambda tx: tx.create(subgraph))
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 1063, in create
    create(self)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/data.py", line 200, in __db_create__
    records = tx.run(*pq)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/database.py", line 987, in run
    result = self._connector.run(self.ref, cypher, parameters)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/client/__init__.py", line 1424, in run
    return cx.run(tx, cypher, parameters)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/client/http.py", line 245, in run
    rs.audit(tx)
  File "/home/hamza/.local/lib/python3.10/site-packages/py2neo/client/http.py", line 482, in audit
    raise failure
py2neo.errors.ClientError: [Request.InvalidFormat] Could not parse the incoming JSON
```
I have tried to resolve this issue, but couldn't get anywhere. Can you please help me to resolve this issue?

**Comment by ManojKamble19** [comment]
![image](https://user-images.githubusercontent.com/105856868/205371919-104a7f1d-79f6-431c-bfed-a2895ea846d0.png)

Make above changes!

**Comment by Gokulmishra** [comment]
@ManojKamble19 greetings am still facing same issue can you please help what is the error am using python 3.6 , neo4j community 4.4.4 py2neo 2021.2.3

![py2neoerror2](https://user-images.githubusercontent.com/67966130/209519844-3074fa71-cefc-4a10-b2af-0054ccc7a432.png)
